baseURL = 'https://ricardotecpro.github.io/portal_hugo/'
relativeURLs = false
canonifyURLs = false
languageCode = 'en-us'
title = 'Portal de Cursos Computação'
theme = 'relearn'

[params]
  editURL = ""
  showNextPrev = true
  # Color variants
  themeVariant = ["relearn-light", "relearn-dark"]
  customStylesheet = "css/custom.css"

[taxonomies]
  disciplina = 'disciplinas'
  tecnologia = 'tecnologias'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Required for Mermaid and HTML in Markdown
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    guessSyntax = true
    lineNos = true
    style = "monokai"
